### ISSUE TITLE
rfc6901

### ISSUE THREAD

**Issue by k-paxian** [passsy/deep_pick#12]
It will be more idiomatic, to utilize https://tools.ietf.org/html/rfc6901

And what about deep write? It feels like read-only thingy no?

**Comment by passsy** [comment]
Yes, deep_pick is for picking values, read only.

I actually didn't know about RFC6901, I came up with the idea on my own and then discovered that similar libs also exist for other languages ([js](https://github.com/mohsen1/deep_pick), [js](https://github.com/jonschlinkert/deep-pick), [python](https://gist.github.com/toddbirchard/b6f86f03f6cf4fc9492ad4349ee7ff8b)).

If you feel JSON pointers are more idiomatic, use [json_pointer](https://pub.dev/packages/json_pointer). It also supports writing into nested objects.
deep_picks focuses is on parsing the picked value.
