### ISSUE TITLE
Add pick as extensions

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [passsy/deep_pick#14]
```dart
map.pick('key').asDoubleOrNull();
// equivalent to
pick(map, 'key').asDoubleOrNull();
```

**Comment by passsy** [comment]
Usually when using pick, the type of the target is `dynamic` which requires an extension on `T`. This would pop up for every object in auto-completion and should be used with care. I don't think it's justifiable for pick.

Narrowing the type to `Map|List` could be useful, but I don't see many cases where those types are known.

I'd like to propose an alternative:
If a new method `jsonDecodeToPick` would return `Pick` you might not need an extension at all.

```dart
final Pick pick = jsonDecodeToPick(response.data);
final key = pick('key').asDoubleOrNull();
```
