### ISSUE TITLE
Support Firebase Timestamps

### ISSUE THREAD

**Issue by AlwinFassbender** [passsy/deep_pick#56]
When using pick to read data from firebase, `asDateTimeOrThrow()` does not support Firebase's built-in timestamp format. My extension which resolves the issue uses this code:
```dart    
if (value is Timestamp) {
      return timestamp.toDate();
}
```

I guess it could be useful to implement this into the package, as deep_pick is often used to do stuff with Maps returned from Firebase, at least in my case.

**Comment by passsy** [comment]
I wish that would be possible. Unfortunately, that would mean that deep_pick has to depend on `Firebase` which I definitely don't want.

I included the Firebase Timestamp example [in the Readme](https://github.com/passsy/deep_pick#custom-parsers), so it's easy to copy-paste.

I could create a separate package, but that might be overkill for 20LOC
