### ISSUE TITLE
Suggestion: add an option for ListPIck to skip individual items that throw

### ISSUE THREAD

**Issue by JacobMuchow** [passsy/deep_pick#59]
Thanks for this lib! I am working on my first flutter app after being a long-time native iOS/Android (and React) dev. This package does exactly what I want, made my parsing code so much cleaner and better handled.

When parsing a list, I would like to be able to skip an item in the list if that specific item throws. Currently, the behavior is to throw for the entire function if an individual item throws when calling the map function. This isn't always the best behavior, sometimes it is better to "skip" a bad item, ex. if you are consuming data from an unreliable source.

I think this functionality could be added fairly easily following your API patterns by adding something like `T? Function(RequiredPick pick, PickException e)? whenThrow` to your parameter options in the NullableListPick extension.

I made an extension in my code that modifies the class to add this. Happy to make a contribution if you are interested.

Changes to _parse function:

```dart
  List<T> _parse<T>(T Function(RequiredPick) map,
      {T Function(Pick pick)? whenNull,
      T? Function(RequiredPick pick, PickException e)? whenThrow}) {
    final value = required().value;
    if (value is List) {
      final result = <T>[];
      var index = -1;
      for (final item in value) {
        index++;
        if (item != null) {
          final picked =
              RequiredPick(item, path: [...path, index], context: context);

          try {
            result.add(map(picked));
          } on PickException catch (e) {
            if (whenThrow == null) {
              rethrow;
            }
            final res = whenThrow(picked, e);
            if (res != null) {
              result.add(res);
            }
          }

          continue;
        }
        if (whenNull == null) {
          // skip null items when whenNull isn't provided
          continue;
        }
        try {
          final pick = Pick(null, path: [...path, index], context: context);
          result.add(whenNull(pick));
          continue;
        } catch (e) {
          // ignore: avoid_print
          print(
            'whenNull at location $debugParsingExit index: $index crashed instead of returning a $T',
          );
          rethrow;
        }
      }
      return result;
    }
    throw PickException(
      'Type ${value.runtimeType} of $debugParsingExit can not be casted to List<dynamic>',
    );
  }
```

Usage:

```dart
    final events = pick(jsonData).asListOrThrow(
      (pick) => TFEvent.fromPick(pick),
      whenThrow: (pick, e) {
        print("Error parsing event from json list. $e");
        return null;
      },
    );
```

For my particular case, I'm just wanting to log an error but still get a list with the other n-1 items.

**Comment by passsy** [comment]
Thanks for the suggestion.

I've ran into the same scenario but solved it with a plain try-catch.

```dart
final events = pick(jsonData).asListOrThrow(
  (pick) {
    try { 
      return TFEvent.fromPick(pick);
    catch (e) {
      print("Error parsing event from json list. $e");
      return null;
    }
  }.whereNotNull().toList().
);
```

You could alternatively change `TFEvent.fromPick(pick)` to return `TFEvent?`, and return `null` when parsing fails.

Does that help?

**Comment by JacobMuchow** [comment]
That does do the trick! Thanks for the suggestion.

I didn't have `whereNotNull()` available but `whereType<TFEvent>()` works just as well. Still getting used to Dart ;)

**Comment by passsy** [comment]
You can get `whereNotNull()` from [`package:collection`](https://pub.dev/documentation/collection/latest/collection/IterableNullableExtension/whereNotNull.html)
