### ISSUE TITLE
maintenance update

### ISSUE THREAD

**Issue by VittorioParagallo** [passsy/deep_pick#60]
Hello, 
i would like to ask if this package is still maintained or everybody moved to a better solution. I just discovered it and i'm thinkin about replacing freezed by hand with the help of this package., but at the same time i see that there are some unclosed old issues and last update was more than a year ago. Is the package still active? will it be maintained? is there any plan?
Tnx in advance

**Comment by passsy** [comment]
The package is feature complete and in a very usable state. We use it every day at @phntmxyz

The open issues are nice-to-have and haven't made it to the top of my priority list. I welcome community PRs and will help getting them integrated.

I'm happy to see how you would use deep_pick in your project ✌️
